import type { Metadata } from "next";
import AuthProvider from '@/Context/Authprovider';
import { Toaster } from "@/components/ui/sonner";
import Navbar from '@/components/navbar';
import './globals.css'; // Fixed import syntax (removed @ and corrected path)


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased min-h-screen bg-gray-900 text-white">
        <AuthProvider>
          <Navbar />
          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
          <Toaster 
            position="top-right"
            theme="dark"
            richColors
          />
        </AuthProvider>
      </body>
    </html>
  );
}